[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "NODE_ENV=production npx nuxt generate"

[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_BUILD_FROM_SOURCE = "true"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "nuxt"

[functions]
  included_files = ["netlify/functions/files/**"]
