[build]
  command = "corepack disable && npx -y pnpm@10.13.1 install --ignore-scripts=false --no-frozen-lockfile && npx -y pnpm@10.13.1 run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.1"

[dev]
  command = "pnpm run dev"
  port = 3000
  targetPort = 3000
  framework = "nuxt"
