[build]
  publish = "dist"
  functions = "netlify/functions"
  command = "nuxt generate"  # Nuxt 2'de direkt `nuxt generate` kullanılır

[build.environment]
  NODE_VERSION = "16"  # Vue 2 + Nuxt 2 için uyumlu sürüm
  NODE_OPTIONS = "--openssl-legacy-provider"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_CONFIG_BUILD_FROM_SOURCE = "true"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  framework = "nuxt"

[functions]
  included_files = ["netlify/functions/files/**"]
