[build]
  command = "corepack disable && npm i -g pnpm@10.13.1 && pnpm approve-builds --all && pnpm install --no-frozen-lockfile && pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.1"

[dev]
  command = "pnpm run dev"
  port = 3000
  targetPort = 3000
  framework = "nuxt"
